### ISSUE TITLE
Running tvm_cli on yolo_v2_tiny Results in Error

### ISSUE THREAD

**Issue by JWhitleyWork** [autowarefoundation/modelzoo#40]
I attempted to build the `yolo_v2_tiny/tensorflow_fp32_coco` network with the following command:

```
docker run -it --rm -v $(pwd):$(pwd) -w $(pwd) -u $(id -u ${USER}):$(id -g ${USER}) --device /dev/nvidia0:/dev/nvidia0 autoware/model-zoo-tvm-cli:latest compile --config ./definition.yaml --output_path .
```

This resulted in the following error:

```
Traceback (most recent call last):
  File "/tvm_cli/tvm_cli", line 282, in <module>
    locals()[parsed_args.command]()
  File "/tvm_cli/tvm_cli", line 258, in compile
    compile_model(info)
  File "/tvm_cli/tvm_cli", line 156, in compile_model
    outputs=info['output_names'])
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.0-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 3526, in from_tensorflow
    mod, params = g.from_tensorflow(graph, layout, shape, outputs)
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.0-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2950, in from_tensorflow
    func = self._get_relay_func(graph, layout=layout, shape=shape, outputs=outputs)
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.0-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 2914, in _get_relay_func
    self._backtrack_construct(node.name)
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.0-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 3456, in _backtrack_construct
    op = self._convert_operator(node.op, inputs, attr, self._graph)
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.0-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 3315, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params, self._mod)
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.0-py3.6-linux-x86_64.egg/tvm/relay/frontend/tensorflow.py", line 279, in _impl
    )(inputs, attr)
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.0-py3.6-linux-x86_64.egg/tvm/relay/frontend/common.py", line 430, in __call__
    return get_relay_op(op_name)(*inputs, **new_attrs)
TypeError: max_pool2d() got an unexpected keyword argument 'explicit_paddings'
```

I am running on Pop!_OS 21.04 (basically Ubuntu 21.04) with Docker version 20.10.2 and an Nvidia RTX 2060 SUPER with driver version 460.73.01. CUDA is not installed.

**Comment by JWhitleyWork** [comment]
Note: Installing all of the pre-requisites on my host machine and running `./tvm_cli.py compile --config ../../perception/camera_obstacle_detection/yolo_v2_tiny/tensorflow_fp32_coco/definition.yaml --output_path .` from the scripts/tvm_cli directory produces the same error.

**Comment by JWhitleyWork** [comment]
Additionally, running the command `./tvm_cli.py compile --config ../../perception/lidar_obstacle_detection/point_pillars_pfe/onnx_fp32_kitti/definition.yaml --output_path .` to compile the `point_pillars` NN completes successfully.

**Comment by ambroise-arm** [comment]
@JWhitleyWork the `autoware/model-zoo-tvm-cli:latest` is actually out of date. I can reproduce the issue with it. It has been fixed in `:bleedingedge`, can you confirm?

**Comment by LiyouZhou** [comment]
1.0.0 have been tagged, so the latest tag is updated. https://hub.docker.com/r/autoware/model-zoo-tvm-cli/tags?page=1&ordering=last_updated

@JWhitleyWork are you happy for this to be closed?
